//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPOBOX.OSC.TeamsTool.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOPOBOX.OSC.TeamsTool.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle Datei: {0}..
        /// </summary>
        internal static string CreateFileMessage {
            get {
                return ResourceManager.GetString("CreateFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim erstellen der Datei: {0}.
        /// </summary>
        internal static string CreatingFileErrorMessage {
            get {
                return ResourceManager.GetString("CreatingFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei erstellt: {0}.
        /// </summary>
        internal static string CreatingFileSuccessMessage {
            get {
                return ResourceManager.GetString("CreatingFileSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim auslesen der Datei: .
        /// </summary>
        internal static string ErrorReadingFileMessage {
            get {
                return ResourceManager.GetString("ErrorReadingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!-- Diese Datei wurde automatisch Generiert von [APP_NAME] [APP_VERSION] am [GEN_DATE] [GEN_TIME] --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;title&gt;[GEN_TITLE] - generated with [APP_NAME] geotopo AG, GEOBOX AG&lt;/title&gt;
        ///&lt;link href=&quot;http://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///*, body {
        ///	font-family: Lato,sans-serif,Helvetica;
        ///	font-size: 14Px;
        ///	padding-top: 0px;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlTemplate {
            get {
                return ResourceManager.GetString("htmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPOBOX_Log_{0}.log.
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Einträge in der Liste vorhanden..
        /// </summary>
        internal static string NoEntriesInListFoundMessage {
            get {
                return ResourceManager.GetString("NoEntriesInListFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim lesen der Datei: {0}.
        /// </summary>
        internal static string ReadFromFileErrorMessage {
            get {
                return ResourceManager.GetString("ReadFromFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lese Datei: {0}.
        /// </summary>
        internal static string ReadFromFileMessage {
            get {
                return ResourceManager.GetString("ReadFromFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei gelesen: {0}.
        /// </summary>
        internal static string ReadFromFileSuccessMessage {
            get {
                return ResourceManager.GetString("ReadFromFileSuccessMessage", resourceCulture);
            }
        }
    }
}
