//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPOBOX.OSC.TeamsTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOPOBOX.OSC.TeamsTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivierung von Kanal beginnt..
        /// </summary>
        internal static string ArchivingChannelBeginMessage {
            get {
                return ResourceManager.GetString("ArchivingChannelBeginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} werden archiviert.
        /// </summary>
        internal static string BeginArchivingChannelItemMessage {
            get {
                return ResourceManager.GetString("BeginArchivingChannelItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} werden migriert.
        /// </summary>
        internal static string BeginMigrateChannelItemMessage {
            get {
                return ResourceManager.GetString("BeginMigrateChannelItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket.
        /// </summary>
        internal static string BucketName {
            get {
                return ResourceManager.GetString("BucketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Aufgabe mit dem Titel {0} wurde im Bucket {1} erstellt..
        /// </summary>
        internal static string CreatedPlannerTaskMessage {
            get {
                return ResourceManager.GetString("CreatedPlannerTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sind archiviert: {1}.
        /// </summary>
        internal static string EndArchivingChannelItemMessage {
            get {
                return ResourceManager.GetString("EndArchivingChannelItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Migrationsmodus für den Kanal {0}, konnte nicht gesetzt werden!.
        /// </summary>
        internal static string FaultedChangeMigrationModeMessage {
            get {
                return ResourceManager.GetString("FaultedChangeMigrationModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie alle Pflichtfelder (*) im Formular aus..
        /// </summary>
        internal static string FirstFillRequiredFieldsMessage {
            get {
                return ResourceManager.GetString("FirstFillRequiredFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Verzeichnisse vorhanden..
        /// </summary>
        internal static string FolderIsEmptyMessage {
            get {
                return ResourceManager.GetString("FolderIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPOBOX Teams Tool.
        /// </summary>
        internal static string genModulName {
            get {
                return ResourceManager.GetString("genModulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ausgewählt: {1}.
        /// </summary>
        internal static string IsSelectedMessage {
            get {
                return ResourceManager.GetString("IsSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einlesen der Dateien aus dem Verzeichnis: {0}.
        /// </summary>
        internal static string ListFilesMessage {
            get {
                return ResourceManager.GetString("ListFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einlesen der Verzeichnisse: {0}.
        /// </summary>
        internal static string ListFoldersMessage {
            get {
                return ResourceManager.GetString("ListFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kanäle des Teams &quot;{0}&quot; werden geladen..
        /// </summary>
        internal static string LoadChannelsOfTeamMessage {
            get {
                return ResourceManager.GetString("LoadChannelsOfTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte melden Sie sich an, um diesen Vorgang durchführen zu können..
        /// </summary>
        internal static string LoginFirstBeforeExecuteMessage {
            get {
                return ResourceManager.GetString("LoginFirstBeforeExecuteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Aufgabe mit dem Titel {0} konnte nicht im Bucket {1} erstellt werden..
        /// </summary>
        internal static string NotCreatedPlannerTaskMessage {
            get {
                return ResourceManager.GetString("NotCreatedPlannerTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein/e {0} ausgewählt..
        /// </summary>
        internal static string NotSelectedWarningMessage {
            get {
                return ResourceManager.GetString("NotSelectedWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        internal static string PlannerName {
            get {
                return ResourceManager.GetString("PlannerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vordefinierte Tasks.
        /// </summary>
        internal static string PredefinedTaskName {
            get {
                return ResourceManager.GetString("PredefinedTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktname.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel wurde wie folgt zusammengesetzt: {0}.
        /// </summary>
        internal static string ReplacedTitleMessage {
            get {
                return ResourceManager.GetString("ReplacedTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Pflichtfelder (*) sind ausgefüllt..
        /// </summary>
        internal static string RequiredFieldsIsOkMessage {
            get {
                return ResourceManager.GetString("RequiredFieldsIsOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Verzeichnis gewählt..
        /// </summary>
        internal static string SavePathIsEmptyMessage {
            get {
                return ResourceManager.GetString("SavePathIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine/n {0} aus der Auswahlliste..
        /// </summary>
        internal static string SelectAnyItemFromListMessage {
            get {
                return ResourceManager.GetString("SelectAnyItemFromListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis zur Archivierung: .
        /// </summary>
        internal static string SelectedSavePathMessage {
            get {
                return ResourceManager.GetString("SelectedSavePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team-Liste importiert..
        /// </summary>
        internal static string TeamListImportetMessage {
            get {
                return ResourceManager.GetString("TeamListImportetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es muss ein Titel angegeben werden..
        /// </summary>
        internal static string TitleIsEmptyWarningMessage {
            get {
                return ResourceManager.GetString("TitleIsEmptyWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein Benutzer angemeldet. Bitte zuerst einloggen..
        /// </summary>
        internal static string UserIsNotLoggedInMessage {
            get {
                return ResourceManager.GetString("UserIsNotLoggedInMessage", resourceCulture);
            }
        }
    }
}
